# Generated by Django 6.0.3 on 2026-04-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_monitorlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='monitorlog',
            index=models.Index(fields=['timestamp'], name='monitors_mo_timesta_42abe1_idx'),
        ),
    ]
