# Generated by Django 6.0.3 on 2026-04-09 09:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_monitorlog_monitors_mo_timesta_42abe1_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monitor',
            new_name='Endpoint',
        ),
        migrations.RenameModel(
            old_name='MonitorLog',
            new_name='EndpointLog',
        ),
        migrations.RenameIndex(
            model_name='endpointlog',
            new_name='monitors_en_timesta_983335_idx',
            old_name='monitors_mo_timesta_42abe1_idx',
        ),
    ]
